name: flutter_map_marker_cluster_example
description: Example for Flutter Map Marker cluster

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: #">=0.13.1 <1.0.0"
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: master
  flutter_map_marker_cluster:
    path: ../
  cupertino_icons: ^1.0.2
  latlong2: ^0.8.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
