name: flutter_map_marker_cluster_example
description: Example for Flutter Map Marker cluster

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_marker_cluster:
    path: ../
  cupertino_icons: ^1.0.5
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
