name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 0.4.0

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=0.13.1 <1.0.0"
  latlong2: ^0.8.0
  flutter_map_marker_popup: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

