name: flutter_map_marker_cluster
description:
  A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 0.3.2

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  flutter_map_marker_popup: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
